PROJECT_HEADERS = {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    "cookie": "i18n_redirected=en; sessionid=9xms609xo9yrnfbh6ua8sxnmbzapgzt5; csrftoken=2rGbYWva7MxxMivz25Se1Sthvhsya2uG",
    "origin": "https://doccano.prod.caresage.ai",
    "priority": "u=1, i",
    "referer": "https://doccano.prod.caresage.ai/v1/projects/create",
    "sec-ch-ua": '"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Linux"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "x-csrftoken": "2rGbYWva7MxxMivz25Se1Sthvhsya2uG",
    "Authorization": "Basic YWRtaW46QWRtaW4xMjM=",
}
PROCESS_HEADERS = {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "i18n_redirected=en; sessionid=9xms609xo9yrnfbh6ua8sxnmbzapgzt5; csrftoken=2rGbYWva7MxxMivz25Se1Sthvhsya2uG",
    "origin": "https://doccano.prod.caresage.ai",
    "priority": "u=1, i",
    "referer": "https://doccano.prod.caresage.ai/v1/projects/project_id/dataset/import",
    "sec-ch-ua": '"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Linux"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "x-csrftoken": "2rGbYWva7MxxMivz25Se1Sthvhsya2uG",
}
UPLOAD_HEADERS = {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    "cookie": "i18n_redirected=en; sessionid=9xms609xo9yrnfbh6ua8sxnmbzapgzt5; csrftoken=2rGbYWva7MxxMivz25Se1Sthvhsya2uG",
    "origin": "https://doccano.prod.caresage.ai",
    "priority": "u=1, i",
    "referer": "https://doccano.prod.caresage.ai/projects/project_id/dataset/import",
    "sec-ch-ua": '"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Linux"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "x-csrftoken": "2rGbYWva7MxxMivz25Se1Sthvhsya2uG",
}
