class DataConstants:
    DEID_PROCESSED_DIR = ""
    PROCESSED_SENTENCES_DIR = ""
    TAGGED_SENTECNES_MACHINE_DIR = ""
    TAGGED_SENTECNES_HUMAN_DIR = ""
    TAGGED_SENTECNES_DOCCANO_DIR = ""
    METRICS_DIR = ""