serialize:

# inp-files (tagged sentences) are present in {root}/taggedsentences(machine_readable)
# out-files (doccano annotations) will be stored in {root}/taggedsentences(doccano_readable)

# for visulizing data on doccano with only LLM based annotations
  - etl: 'annotated_sentences_to_doccano_annotations'
    root: 'data'
    factory: "annotations_to_doccano_annotations"
    inp-file: '2006_unannotated_taggedsentences.ndjson'
    out-file: '2006_unannotated_taggedsentences.ndjson'

# for visulizing data on doccano with LLM based annotations and ground truth annotations
  - etl: 'compare_sentence_annotations_to_doccano_annotations'
    root: 'data'
    factory: "annotations_to_doccano_annotations"
    inp-file: '2006_annotated_taggedsentences.ndjson'
    out-file: '2006_annotated_taggedsentences.ndjson'

  - etl: 'compare_sentence_annotations_to_doccano_annotations'
    root: 'data'
    factory: "annotations_to_doccano_annotations"
    inp-file: '2014_taggedsentences.ndjson'
    out-file: '2014_taggedsentences.ndjson'
