serialize:

# inp-files (clinical notes) are present in {root}/clinicalnotes
# out-files (clinical sentences) will be stored in {root}/clinicalsentences

# for extracting sentences from any clinical notes - with ground annotation datasets
  - etl: 'annotated_clinical_notes_to_sentences'
    root: 'data'
    factory: 'clinicalnotes_to_sentences'
    inp-file: '2006_annotated_clinicalnote.ndjson'
    out-file: '2006_annotated_clinicalsentences.ndjson'
    sentence-extractor: 'spacy_with_basic'  # you can replace it with your(any) algoritm

  - etl: 'annotated_clinical_notes_to_sentences'
    root: 'data'
    factory: 'clinicalnotes_to_sentences'
    inp-file: '2014_clinicalnote.ndjson'
    out-file: '2014_clinicalsentences.ndjson'
    sentence-extractor: 'spacy_with_basic'  # you can replace it with your(any) algoritm

# for extracting sentences from any clinical notes - only clinical notes datasets
  - etl: 'unannotated_clinical_notes_to_sentences'
    root: 'data'
    factory: 'clinicalnotes_to_sentences'
    inp-file: '2006_unannotated_clinicalnote.ndjson'
    out-file: '2006_unannotated_clinicalsentences.ndjson' 
    sentence-extractor: 'spacy_with_basic'  # you can replace it with your(any) algoritm