serialize:

# for extracting sentences from any clinical notes - with ground annotation datasets
  - etl: 'annotated_clinicalnotes_to_sentences'
    factory: 'clinicalnotes_to_sentences'
    inp-file: 'copy_DEID_PROCESSED_DIR_name_from_constant.py/2006_annotated.ndjson'
    out-file: 'copy_PROCESSED_SENTENCES_DIR_name_from_constant.py/2006_annotated_sentences.ndjson'
    sentence-extractor: 'spacy_with_basic'  # you can replace it with your(any) algoritm

  - etl: 'annotated_clinicalnotes_to_sentences'
    factory: 'clinicalnotes_to_sentences'
    inp-file: 'copy_DEID_PROCESSED_DIR_name_from_constant.py/2014.ndjson'
    out-file: 'copy_PROCESSED_SENTENCES_DIR_name_from_constant.py/2014.ndjson'
    sentence-extractor: 'spacy_with_basic'  # you can replace it with your(any) algoritm

# for extracting sentences from any clinical notes - only clinical notes datasets
  - etl: 'unannotated_clinicalnotes_to_sentences'
    factory: 'clinicalnotes_to_sentences'
    inp-file: 'copy_DEID_PROCESSED_DIR_name_from_constant.py/2006_unannotated.ndjson'
    out-file: 'copy_PROCESSED_SENTENCES_DIR_name_from_constant.py/2006_unannotated_sentences.ndjson' 
    sentence-extractor: 'spacy_with_basic'  # you can replace it with your(any) algoritm