serialize:

# for extracting clinical notes from 2006_annotated.xml
  - etl: 'annotated_raw_clinical_notes_i2b2_2006'
    factory: 'dataset_to_clinicalnotes'
    inp-file: 'data/SampleI2B2Data/2006_annotated.xml'
    out-file: 'copy_DEID_PROCESSED_DIR_name_from_constant.py/2006_annotated.ndjson'

# for extracting clinical notes from 2006_unannotated.xml
  - etl: 'unannotated_raw_clinical_notes_i2b2_2006'
    factory: 'dataset_to_clinicalnotes'
    inp-file: 'data/SampleI2B2Data/2006_unannotated.xml'
    out-file: 'copy_DEID_PROCESSED_DIR_name_from_constant.py/2006_unannotated.ndjson'

# for extracting clinical notes from 2014.xml
  - etl: 'annotated_clinical_notes_i2b2_2014'
    factory: 'dataset_to_clinicalnotes'
    inp-file: 'data/SampleI2B2Data/2014.xml'
    out-file: 'copy_DEID_PROCESSED_DIR_name_from_constant.py/2014.ndjson'