serialize:
  
# inp-files (xml files) are present in {root}/I2B2Data
# out-files (clinical notes) will be stored in {root}/clinicalnotes

# for extracting clinical notes from 2006_annotated.xml
  - etl: 'annotated_raw_clinical_notes_i2b2_2006'
    root: 'data'
    factory: 'dataset_to_clinicalnotes'
    inp-file: '2006_annotated.xml'
    out-file: '2006_annotated_clinicalnote.ndjson'

# for extracting clinical notes from 2006_unannotated.xml
  - etl: 'unannotated_raw_clinical_notes_i2b2_2006'
    root: 'data'
    factory: 'dataset_to_clinicalnotes'
    inp-file: '2006_unannotated.xml'
    out-file: '2006_unannotated_clinicalnote.ndjson'

# for extracting clinical notes from 2014.xml
  - etl: 'annotated_clinical_notes_i2b2_2014'
    root: 'data'
    factory: 'dataset_to_clinicalnotes'
    inp-file: '2014.xml'
    out-file: '2014_clinicalnote.ndjson'