# for tagging sentences from any 2006 DeID SmokingStatus only clinical sentences
  - etl: 'unannotated_sentences_tagging_2006i2b2'
    factory: 'sentences_to_annotations'
    inp-file: 'copy_PROCESSED_SENTENCES_DIR_name_from_constant.py/2006_unannotated_sentences.ndjson'
    out-file: 'copy_TAGGED_SENTECNES_MACHINE_DIR_name_from_constant.py/2006_unannotated_sentences.ndjson'
    sentence-tagging: 'gpt'  # you can replace it with your(any) algoritm
    model: "gpt-4o"   # you can replace it with any model_name

# for tagging sentences from any 2006 DeID SmokingStatus clinical sentences with ground annotation
  - etl: 'annotated_sentences_tagging_2006i2b2'
    factory: 'sentences_to_annotations'
    inp-file: 'copy_PROCESSED_SENTENCES_DIR_name_from_constant.py/2006_annotated_sentences.ndjson'
    out-file: 'copy_TAGGED_SENTECNES_MACHINE_DIR_name_from_constant.py/2006_annotated_sentences.ndjson'
    sentence-tagging: 'gpt'  # you can replace it with your(any) algoritm
    model: "gpt-4o"  # you can replace it with any model_name

# for tagging sentences from any 2014 DeID heart disease clinical sentences with ground annotation
  - etl: 'annotated_sentences_tagging_2014i2b2'
    factory: 'sentences_to_annotations'
    inp-file: 'copy_PROCESSED_SENTENCES_DIR_name_from_constant.py/2014.ndjson'
    out-file: 'copy_TAGGED_SENTECNES_MACHINE_DIR_name_from_constant.py/2014.ndjson'
    sentence-tagging: 'gpt'  # you can replace it with your(any) algoritm
    model: "gpt-4o"  # you can replace it with any model_name