serialize:

# inp-files (clinical sentences) are present in {root}/clinicalsentences
# out-files (tagged sentences) will be stored in {root}/taggedsentences(machine_readable)

# for tagging sentences from any 2006 DeID SmokingStatus only clinical sentences
  - etl: 'unannotated_sentences_tagging_2006i2b2'
    root: 'data'
    factory: 'sentences_to_annotations'
    inp-file: '2006_unannotated_clinicalsentences.ndjson'
    out-file: '2006_unannotated_taggedsentences.ndjson'
    sentence-tagging: 'gpt'  # you can replace it with your(any) algoritm
    model: "gpt-4o"   # you can replace it with any model_name

# for tagging sentences from any 2006 DeID SmokingStatus clinical sentences with ground annotation
  - etl: 'annotated_sentences_tagging_2006i2b2'
    root: 'data'
    factory: 'sentences_to_annotations'
    inp-file: '2006_annotated_clinicalsentences.ndjson'
    out-file: '2006_annotated_taggedsentences.ndjson'
    sentence-tagging: 'gpt'  # you can replace it with your(any) algoritm
    model: "gpt-4o"  # you can replace it with any model_name

# for tagging sentences from any 2014 DeID heart disease clinical sentences with ground annotation
  - etl: 'annotated_sentences_tagging_2014i2b2'
    root: 'data'
    factory: 'sentences_to_annotations'
    inp-file: '2014_clinicalsentences.ndjson'
    out-file: '2014_taggedsentences.ndjson'
    sentence-tagging: 'gpt'  # you can replace it with your(any) algoritm
    model: "gpt-4o"  # you can replace it with any model_name